image:
  file: .gitpod.Dockerfile

tasks:
  - name: Create KIND Cluster
    command: |

      kind create cluster --config=kind-config.yaml || true
      kubectl get nodes

vscode:
  extensions:
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - HashiCorp.terraform
