tasks:
  - name: Install Tools
    init: |
      sudo apt-get update -y
      
      # Install Docker
      sudo apt-get install -y docker.io
      sudo usermod -aG docker gitpod
      sudo systemctl start docker

      # Install kubectl
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      # Install KIND
      curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
      chmod +x ./kind
      sudo mv ./kind /usr/local/bin/kind

      # Install Terraform
      sudo apt-get install -y gnupg software-properties-common
      wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      sudo apt-get update && sudo apt-get install -y terraform

  - name: Create KIND Cluster
    command: |
      kind create cluster --config=kind-config.yaml
      kubectl get nodes

vscode:
  extensions:
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - HashiCorp.terraform
